#!/bin/bash
set -e; set -u; set -o pipefail

SRC=source
BUILD=build
VENV=.venv

if [[ ! ${1-} ]]; then
    echo "Usage: run <build/server>"
    exit 1
fi

if ! diff -q $VENV/requirements.txt requirements.txt; then
    python3 -m venv $VENV
    source $VENV/bin/activate
    python3 -m pip install -r requirements.txt
    cp requirements.txt $VENV/requirements.txt
else
    source $VENV/bin/activate
fi

case $1 in
    build ) sphinx-build     $SRC $BUILD ;;
    server) sphinx-autobuild $SRC $BUILD ;;
    *) echo -e "Unsupported command: $1.\nSupported commands are build and server"; exit 1 ;;
esac
