#!/bin/bash
set -e; set -u; set -o pipefail
BLUE='\033[0;34m'; RED='\033[0;31m'; GREEN='\033[0;32m'; NC='\033[0m';
ERROR=

VENV=tests/.venv
TESTS=tests

if ! diff -q $VENV/requirements.txt $TESTS/requirements.txt; then
    python3 -m venv $VENV
    source $VENV/bin/activate
    python3 -m pip install -r $TESTS/requirements.txt
    cp $TESTS/requirements.txt $VENV/requirements.txt
else
    source $VENV/bin/activate
fi

cmake -B build/Release -D CMAKE_BUILD_TYPE=Release
cmake --build build/Release

build/Release/bin/mdb import $TESTS/update/data.ttl $TESTS/update/tmp

python3 scripts/update.py

rm -rf $TESTS/update/tmp
